### ISSUE TITLE
About inputting backslash '\'

### ISSUE THREAD

**Issue by tanguband** [backwardsEric/hengband#15]
The backslash input on the JIS keyboard is option + 'yen' key, but please change this to input with the 'yen' key.
Reason: Backslash is often used in macros, so I want to make it easier to enter. 
<img width="382" alt="key codes" src="https://user-images.githubusercontent.com/17109188/109893282-b2cfc480-7cce-11eb-8169-9605edd026b3.png">

**Comment by backwardsEric** [comment]
It's a reasonable request as the yen symbol is likely only to be used as a macro trigger.

I'd prefer not to have to put in a special exception in the key handling.  So, satisfying the request would likely take a fair amount of effort to implement (load a map, probably locale-specific, of keys to be handled as exceptions; use that map in the key handling; ideally, have some way for the user to disable the map or customize it with one of their own).  I don't know if I'll get around to it soon.

**Comment by tanguband** [comment]
Thank you for your reply.
This is a special requirement for a Japanese environment, so you don't need to force us to support it.
We will try to support it in our environment.
