### ISSUE TITLE
Is it possible to use c++20 with clang on Mac?

### ISSUE THREAD

**Issue by tanguband** [backwardsEric/hengband#18]
The official Hengband development team mentioned that it would be useful to be able to use C++20 features.
Is it possible to use c++20 with clang on Mac?

**Comment by backwardsEric** [comment]
According to https://clang.llvm.org/cxx_status.html , there's partial support for c++20 with the version of clang, 12.0.0, included in the most recently released Xcode, 12.4.  They would have to cross-check that list with the feature they wanted to use to see if it was supported.

**Comment by tanguband** [comment]
Thank you for your answer. I will look into the corresponding functions.
