### ISSUE TITLE
Freezes after "new" or "open" in Japanese version

### ISSUE THREAD

**Issue by tanguband** [backwardsEric/hengband#19]
3.0.0Alpha35

Environment builds the latest version of the macos-develop branch using macos 11.5.1 commandline tools
Previously the build was successful and it started normally
Freezes when launching a successful build application after several build failures

The screen at the time of freeze is in the following state
please wait
Loading version 3.0.0 save data (SVAE5 format)
Dungeon is being restored

This issue only occurs in the main account and when I switch to the sub account it starts normally
After this state, V2.2.1 and V1.6.2 applications will not start either.

The same phenomenon has occurred with macos14 that I used before.

The error message when booting from terminal is as follows

$ ./hengband
2021-08-19 12: 36: 07.745 hengband [45514: 4719196] *** Assertion failure in-[NSThemeFrame initWithFrame:], NSView.m: 1353
2021-08-19 12: 36: 07.748 hengband [45514: 4719196] Frame containing non-finite values ​​{{0, 0}, {9.5531391950081541e + 99, inf}} passed to [NSThemeFrame initWithFrame :]
Terminated: 15

If you know the solution, please let me know.

**Comment by backwardsEric** [comment]
Given that it works in one account and not another, I would suspect something has gone wrong with the stored preferences in ~/Library/jp.osdn.hengband.plist .  You can get a human-readable version of those from the command line by running this in a Terminal (which puts the output in ~/Desktop/hengband-settings.txt):

```
defaults read ~/Library/Preferences/jp.osdn.hengband.plist > ~/Desktop/hengband-settings.txt
```

Could you post what those settings are for the account that has trouble running hengband?

You can clear out the settings by running this in a Terminal:

```
defaults delete ~/Library/Preferences/jp.osdn.hengband.plist
```

That may resolve your immediate problem.

**Comment by tanguband** [comment]
Thank you for suggesting a solution

After deleting the plist, it started up safely

For reference, I will attach the plist before deletion

I hope it will help you in future development. 

[hengband-settings.txt](https://github.com/backwardsEric/hengband/files/7018344/hengband-settings.txt)

**Comment by tanguband** [comment]
additional information

I used to manually delete "plist" using "Finder".

After checking, it seems that it will not disappear completely unless it is deleted with the "defaults delete" command.

This seems to be the cause.

**Comment by backwardsEric** [comment]
In the account where Hengband worked, were you using the RictyDiminished-Bold font for the subwindows as well or were you using something else?  Had something changed about that font (uninstalled, reinstalled, ...) around the time Hengband started having trouble?

**Comment by backwardsEric** [comment]
With a font specified in the preferences that wasn't available on the system, I got similar symptoms to what you reported.  The changes in https://github.com/backwardsEric/hengband/commit/69beaff3f0f8481a541eaacc52ba64cebfd3a90f should make the front-end for Hengband 3 more robust in that case.  I'll port those changes to the front ends for 2.2.1 and 1.6.2 as well.

**Comment by tanguband** [comment]
The font remained standard in the other account that was started.
Ricty Diminished-Bold font was decommissioned in Font Book for accounts that didn't start.
It seems that the cause has been clarified.
Thank you for the solution.

**Comment by backwardsEric** [comment]
The changes for 1.6.2 and 2.2.1 have been released so I'll close this.
