### ISSUE TITLE
Request: Replace the history of Hengband

### ISSUE THREAD

**Issue by Hourier** [backwardsEric/hengband#21]
Today, we delete some commits from remote develop branch in Hengband.
That's because there are some problem of rights for music/sound and management for BLOBs.
We'd appreciate that you also delete the commits that many \*.wav and \*.mp3 files were added.
Thank you for your cooperation.

**Comment by backwardsEric** [comment]
If I've understood things correctly, it's just a handful of commits from yesterday that are the issue.  Those have been removed and the branches here that had them (develop and macos-develop) should be in a good state.  If you see that I missed purging something in the commit history for the macos-develop branch (the develop branch just tracks Hengband's develop branch), please let me know.

**Comment by Hourier** [comment]
I checked this develop repository and found no problem.
Thank you for your cooperation!
I close this ticket.
