### ISSUE TITLE
When I investigate an item in the store, the characters are cut off and displayed.

### ISSUE THREAD

**Issue by tanguband** [backwardsEric/hengband#23]
## Environment

--Version: 3.0.0 Alpha53 ( Japanese )

## detail

When I investigate an item in the store, the characters are cut off and displayed.

## Reproducibility procedure

1. Create a new character
2. Enter the '6' store
3. Examine magic items with 'x' command (this time 'e) sleep monster' )
4. Characters in the middle are cut off and displayed 

<img width="763" alt="JP_01" src="https://user-images.githubusercontent.com/17109188/156090918-7a71bd11-085c-4de0-b6a1-507efd3b9add.png">
<img width="763" alt="JP_02" src="https://user-images.githubusercontent.com/17109188/156090934-f0591651-e5f5-44bc-b1e8-ad023ebde52e.png">

## Supplementary information
The same is true for version 1.6.2 & 2.2.1

**Comment by tanguband** [comment]
When I tried it again, I couldn't reproduce it in any version.
There may be a problem with my environment
This issue will be closed as it is not a bug
I apologize to you for a fuss over

**Comment by backwardsEric** [comment]
Thanks for the report.  When I checked it, I was getting the same behavior as in the X11 version for the development version of Hengband without the changes for MacOS.
