### ISSUE TITLE
Japanese version cannot be built due to changes in gcc-wrap

### ISSUE THREAD

**Issue by tanguband** [backwardsEric/hengband#24]
After changing gcc-wrap, only the Japanese version fails to build.

Reverted to previous gcc-wrap and build succeeded.

Please help me, as I don't know the cause of this problem.

https://github.com/hengband/hengband/pull/2288

**Comment by tanguband** [comment]
The original development team has fixed the problem and the Japanese version can now be built!

https://github.com/hengband/hengband/pull/2379#pullrequestreview-901022056

**Comment by tanguband** [comment]
After fixing gcc-wrap, the intel Japanese version was successfully built.
Universal version does not seem to build

1. Revert gcc-wrap to previous version

2. env CFLAGS="-g -O2 -arch arm64" CXXFLAGS="-g -O2 -arch arm64" OBJCXXFLAGS="-g -O2 -arch arm64" LDFLAGS="-arch arm64" . /configure --disable-pch --enable-cocoa

3. make install

Universal version built successfully!

Is it possible to have it revert to the previous gcc-wrap?

**Comment by backwardsEric** [comment]
It may be possible to revert gcc-wrap:  I'll want to check why it was changed upstream.  Which version of macOS and Xcode are you using?  A universal build for Japanese works on macOS 11.6.2 running on an Intel processor with Xcode 13.2.1, but the Japanese builds using Github's macOS runner have been failing for a couple of weeks - likely due to this issue.

**Comment by tanguband** [comment]
The reason for the change in gcc-wrap is as follows

https://github.com/hengband/hengband/issues/2286

Reasons for using gcc-wrap

Currently the source code is written in UTF-8 encoding, but when compiling on Linux/MacOS, the internal character encoding needs to be EUC-JP, so a wrapper script called gcc-wrap is used instead of gcc/clang.
Problems with the current conversion method

In gcc-wrap, the UTF-8 source code is backed up once, the source code itself is converted to EUC-JP, gcc/clang is actually called to compile the source code, and after completion, the backup is overwritten with the EUC-JP converted code to return to UTF-8. However, the source code itself is once overwritten to EUC-JP and then reverted back to UTF-8, which is visible in the open editor and causes inconveniences such as the conversion being stored in the undo buffer or ending up in EUC-JP when interrupted with ^C.
Improvement plan

Since it is easy to cause inconveniences when trying to do various things under the src directory, a dedicated build directory should be used.
For example, create a directory called build directly under the hengband directory, copy src/aho/hoge.cpp to build/aho/hoge.cpp with UTF-8 to EUC-JP conversion using a script, invoke gcc in the build directory, and execute Build/aho/hoge.o back to src/aho/hoge.o.
This allows compiling under the src directory without creating extra files or doing any character encoding conversion.

environment

CPU: quad-core 64-bit kabylake
Clang: 13.0.0 build 1300
Git: 2.32.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.2.1-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: N/A

**Comment by tanguband** [comment]
I have confirmed that the Japanese build using the Github macOS runner was successful.

I built it in this environment and it worked!

No modifications seem necessary.

If there is no problem, you can close this page.
