### ISSUE TITLE
add request　lib/pref/pref-mac.prf

### ISSUE THREAD

**Issue by tanguband** [backwardsEric/hengband#25]
Apple keyboard with numeric keypad has function keys up to F19
I want it added after line 50 in lib/pref/pref-mac.prf
T:F17:417f
T:F18:517f
T:F19:617f

**Comment by backwardsEric** [comment]
The change for the version based on Hengband's 3.0.0 alpha versions has been checked into the macos-develop branch.  I'll add similar changes for the 1.6.2 and 2.2.1 branches soon.  I don't know when a binary release incorporating those changes will happen.
