### ISSUE TITLE
About C++20 Support in Apple Clang

### ISSUE THREAD

**Issue by habu1010** [backwardsEric/hengband#26]
We hope to migrate the standard C++ language version of hengband's code base to C++20 in the near future.
Therefore, we need to change the `-std=gnu++17` given in the compile options to `-std=gnu++20` when compiling with clang.
I believe Apple Clang 14 supports this option.

The following line in configure.ac

```
AX_CXX_COMPILE_STDCXX(17, [ext], [mandatory])
```

can you change the 17 to 20 and see if it builds?

We will try to avoid using C++20 features that Apple Clang 14 does not yet support.

**Comment by backwardsEric** [comment]
The current develop branch with configure.ac modified to select C++20 and configured with either `--disable-worldscore --disable-pch` or `--disable-worldscore --disable-pch --disable-japanese` builds with clang 14.0.0 on macOS 12.6.1.  I don't have X11 installed so compilation of the files specific to the X11 front end wasn't tested.  There wasn't any additional warnings beyond what's there when targeting C++17.

On the same system (clang 14.0.0 and macOS 12.6.1) and compiling for compatibility with macOS 10.13, the current macos-develop branch of my fork also builds in either Japanese or English when modified to select C++20.  Building on GitHub's current macos-latest runner (clang 13.0.0 and macOS 11.7.2; that will be clang 14.0.0 and macOS 12.6.2 soon) also worked with my fork.  There's one warning in the Mac-specific code that I'll have to investigate, but you shouldn't hold up using C++20 for that.

**Comment by habu1010** [comment]
Thanks for the detailed report!
It seems to be OK and we will make the change to the compiler language standard to C++20 in the near future.
