### ISSUE TITLE
I want the title screen to be centered in the window as in X11 and Windows.

### ISSUE THREAD

**Issue by tanguband** [backwardsEric/hengband#27]
https://github.com/hengband/hengband/pull/3054

I need to modify src/main-cocoa.mm, can you please respond?

**Comment by backwardsEric** [comment]
With https://github.com/backwardsEric/hengband/commit/ed2b8b5a917eb1723d6e68bb5aa96662016f7a2e , the Cocoa front end should center the splash screen in the window.

**Comment by tanguband** [comment]
Thank you for your response.
