### ISSUE TITLE
About the BGM function

### ISSUE THREAD

**Issue by tanguband** [backwardsEric/hengband#28]
The Windows version supports the BGM function, but is it possible to have the Mac version support it as well?

**Comment by backwardsEric** [comment]
I'd need to more closely look at the implementation of the background music in the Windows front end to know if it could be done in the Mac version.  Playback of the mp3 files is readily available.  One question is how the Windows front end handles when a sound effect is played over the background music or handles transitions between different background music tracks.

**Comment by backwardsEric** [comment]
https://github.com/backwardsEric/hengband/pull/29 implements background music for the Mac front end.  If you want to try it yourself, you'd need those changes and the latest version of https://github.com/backwardsEric/hengband.xtra so the music files from lib/xtra are included in the application.

The Japanese translations for the new strings in the menus and dialogs will need to be improved.  What's there is very crude:  the result of Google Translate with some checking against a Japanese-English dictionary.  The new strings are the "Sound and Music ..." entry in the "Settings" menu and all the strings associated with the dialog that entry opens.  Below are the current screenshots of the English and Japanese versions of that menu and dialog.

If there are any other suggestions about how the background music has been implemented, they'd be appreciated.

![EnglishSettingsMenu](https://user-images.githubusercontent.com/55062581/232845890-1f070dee-139f-4b2c-b98e-4ab3e2740d15.png)
![EnglishSoundAndMusic](https://user-images.githubusercontent.com/55062581/232845928-4b888b2a-78d5-44b5-ab5d-7ff2d0635236.png)
![JapaneseSettingsMenu](https://user-images.githubusercontent.com/55062581/232845966-116160ef-b5d1-4405-b788-f47a7f5a1244.png)
![JapaneseSoundAndMusic](https://user-images.githubusercontent.com/55062581/232846011-f9c02ed7-f798-41b5-abd4-2ba9eea1d64d.png)

**Comment by backwardsEric** [comment]
The changes from the #29 are now merged into the macos-develop branch.  To use them you'll need the latest version of  https://github.com/backwardsEric/hengband.xtra for the lib/xtra submodule.  If everything seems okay with the changes for background music, I'll do a full release that includes these changes after the next the 3.0.0 alpha 79 release for Hengband.
