### ISSUE TITLE
BGM function About the location of the xtra/music folder

### ISSUE THREAD

**Issue by tanguband** [backwardsEric/hengband#31]
Thank you from the bottom of my heart for implementing the BGM function while you are busy.

Currently, the xtra/music folder is located in the application, but we are considering placing it under ~/Documents/Hengband-3.0.0

Compare the pros and cons of both

In application

merit
Distributing only the application eliminates the need for other tasks

Demerit
If you want to use your favorite BGM, you have to rearrange the files each time you update
10 times larger than before when distributed

in document folder

merit
Once set, no further settings are required
Easy access to folders

Demerit
If it is difficult to set only with the application, you need to set it with a script etc.
Initial setup takes time

Both have pros and cons and it's hard to decide.

Can you tell me if you have any good ideas

**Comment by backwardsEric** [comment]
On macOS, another disadvantage to placing the music files outside of the application bundle is the interaction with user's privacy settings (already can get warnings about reading and writing the savefile; the access to the music will be read-only but may still trigger a warning).

I don't have a strong opinion either way.  You and Hengband's developers likely have a better sense of how many people play the game with the music on and whether those people would be deterred by an extra steps to set up the music if it isn't packaged with the application.

**Comment by tanguband** [comment]
I asked the Hengband community how BGM was used, but the usage rate was less than half.
Half of the BGM users also added their own favorite BGM
There seems to be no reason to actively change the specification at this time
I would like to close this issue
If the situation changes and I would like to ask you to consider changing the specifications, I would like to raise a separate issue.
