### ISSUE TITLE
About github actions artifacts

### ISSUE THREAD

**Issue by tanguband** [backwardsEric/hengband#32]
I'm currently uploading and distributing my own built applications to my website for each version update.
After a little research, I found out that github actions has a feature to save and publish built applications.
If possible, could you please make it possible to download the latest version of the application from this site?
Thank you in advance for your consideration.

**Comment by backwardsEric** [comment]
I've added a new workflow, https://github.com/backwardsEric/hengband/blob/macos-develop/.github/workflows/release.yaml , which will automatically build releases with binaries for Japanese and English and a source code archive.  It'll run when there is a push to the macos-develop branch.  The releases it generates will show up on https://github.com/backwardsEric/hengband/releases , be marked as prereleases, and be associated with tags of the form vauto3.0.0-Alpha....  An example of such a release is this one, https://github.com/backwardsEric/hengband/releases/tag/vauto3.0.0-alpha82-4fdf3e852 .

I'll still occasionally, every 6 months or so, manually generate a new release from the 3.0.0 code base that'll get a bit more testing on my part.  Those releases will get direct links on https://backwardseric.github.io/hengband/ .

**Comment by tanguband** [comment]
Thank you for taking the time to respond.
I used to build and distribute it myself every time for Japanese Mac users,
From now on, I would like to refer them to this page.
Thank you from the bottom of my heart.
