### ISSUE TITLE
Is there any problem distributing a macOS version that relies on OpenSSL?

### ISSUE THREAD

**Issue by habu1010** [backwardsEric/hengband#35]
We are currently planning to change from libcurl to cpp-httplib for sending scores to the score server with [this pull request](https://github.com/hengband/hengband/pull/3437).

Since we also plan to implement error reporting and other functions, we need to make cpp-httplib support SSL communication, but cpp-httplib only supports OpenSSL and not LibreSSL, the macOS standard SSL library.

I have already had @tanguband confirm that this PR can be built on macOS by installing OpenSSL with homebrew, but is it possible that the dependence on OpenSSL could be a problem in distributing a pre-built macOS version?

**Comment by backwardsEric** [comment]
From what I've seen so far (but I haven't verified that by building and configuring OpenSSL from scratch), it'll be possible to build the OpenSSL's libssl and libcrypto and package those in Hengband's application bundle.  Hengband would be linked to those libraries and not depend on the player having installed it.  The OpenSSL license would also have to be included in the application bundle, and the Mac front end have a way to view it.  That part should be straightforward to implement.

**Comment by habu1010** [comment]
Thanks for the reply.

Since there seems to be no problem in distributing a package that depends on OpenSSL, we will proceed to use cpp-httplib as planned.
FYI, we will add copyright information for third-party libraries to [THIRD-PIRTY-NOTICES.txt](https://github.com/hengband/hengband/blob/2cfba969a6342d9eeadf095954c8b2f18baef998/THIRD-PARTY-NOTICES.txt) in order to comply with the license terms for redistributing headers and binaries of those libraries.
If you want to add the ability to display copyright information to the macOS front end, this file may help.

**Comment by backwardsEric** [comment]
Looking at it some more, the Legalities section of the Downloads page for OpenSSL gives me some concern:

```
Please remember that export/import and/or use of strong cryptography software, providing cryptography hooks, or even just communicating technical details about cryptography software is illegal in some parts of the world. So when you import this package to your country, re-distribute it from there or even just email technical suggestions or even source patches to the authors or other people you are strongly advised to pay close attention to any laws or regulations which apply to you. The authors of OpenSSL are not liable for any violations you make here. So be careful, it is your responsibility.
```

Based on that and the United States' regulations for export of encryption technology (since that's where I am; though it may also matter where GitHub is incorporated and where their servers are), it'd probably be easier to not package the OpenSSL library with the macOS version and require that the player install it via homebrew.  I could make versions available configured with --disable-worldscore if necessary if players wanted to avoid the requirement of having OpenSSL.

**Comment by habu1010** [comment]
As you say, there are still (somewhat skeletalized) restrictions on the export of software containing encryption functions due to historical reasons.
However, if we try to deal with this issue strictly, we may have to stop statically linking OpenSSL libraries.

For the time being, I think it would be better to deal with this issue as follows.

English version:
Originally, the English version did not have the ability to send scores to the score server, so if you configure it with --disable-worldscore, the library will not be linked.

Japanese version:
Since cpp-httplib originally has a #define macro switch to enable/disable OpenSSL support, set OpenSSL to disabled by default. This way, only HTTP (non-SSL) communication is possible without OpenSSL static linking.

With the above in place, add a configuration such as --enable-ssl to configure and select it to enable it.
Those who need SSL communication functionality should install OpenSSL and build hengband on their own. (Currently hengband does not do HTTP communication other than sending to the score server, so this is not the case.)

This would allow us to distribute the application without static linking OpenSSL and keeping the current functionality.

However, the reason why the current score transmission to the score server does not require OpenSSL is because the server where the score server is installed happens to not support HTTPS, and if HTTPS becomes mandatory, it will not be possible to transmit.
Also, if we implement a new function that uses HTTPS communication (error reporting, etc.), the function cannot be used if the application does not link OpenSSL, so it is just a postponement of the problem.

**Comment by habu1010** [comment]
P.S.

In the meantime, I will soon create a pull request to change cpp-httplib's OpenSSL support to be disabled by default and enabled by the --enable-ssl switch.

**Comment by habu1010** [comment]
I'm not very familiar with the implementation around SSL in macOS, so I'd like to ask, do you know what happens when SSL communication is enabled if we revert to the previous method of communication using libcurl?

I've done a little research and found that on macOS, when using libcurl for SSL communication, there are two ways to do it: through the OS's secure transport (is this through LibreSSL?) and through OpenSSL (installed by homebrew).

Is it possible to use the former when building software using libcurl? And if so, would it be possible to distribute the software without static linking the encryption functionality? If so, I would consider reverting to libcurl.

**Comment by backwardsEric** [comment]
If I compile this,

```
#include <curl/curl.h>
#include <stdio.h>
#include <string.h>

int main(void)
{
        const struct feature_elem { int mask; const char *name; } features[] = {
                { CURL_VERSION_ALTSVC, "alt-svc" },
                { CURL_VERSION_ASYNCHDNS, "AsynchDNS" },
                { CURL_VERSION_BROTLI, "brotli" },
                { CURL_VERSION_DEBUG, "Debug" },
                { CURL_VERSION_GSASL, "gsasl" },
                { CURL_VERSION_GSSAPI, "GSS-API" },
                { CURL_VERSION_HSTS, "HSTS" },
                { CURL_VERSION_HTTP2, "HTTP2" },
                { CURL_VERSION_HTTP3, "HTTP3" },
                { CURL_VERSION_HTTPS_PROXY, "HTTPS-proxy" },
                { CURL_VERSION_IDN, "IDN" },
                { CURL_VERSION_IPV6, "IPv6" },
                { CURL_VERSION_KERBEROS5, "Kerberos" },
                { CURL_VERSION_LARGEFILE, "Largefile" },
                { CURL_VERSION_LIBZ, "libz" },
                { CURL_VERSION_MULTI_SSL, "MultiSSL" },
                { CURL_VERSION_NTLM, "NTLM" },
                { CURL_VERSION_NTLM_WB, "NTLM_WB" },
                { CURL_VERSION_PSL, "PSL" },
                { CURL_VERSION_SPNEGO, "SPNEGO" },
                { CURL_VERSION_SSL, "SSL" },
                { CURL_VERSION_SSPI, "SSPI" },
                { CURL_VERSION_THREADSAFE, "threadsafe" },
                { CURL_VERSION_TLSAUTH_SRP, "TLS-SRP" },
                { CURL_VERSION_CURLDEBUG, "TrackMemory" },
                { CURL_VERSION_UNICODE, "Unicode" },
                { CURL_VERSION_UNIX_SOCKETS, "UnixSockets" },
                { CURL_VERSION_ZSTD, "zstd" },
                { CURL_VERSION_CONV, "Conv" },
                { CURL_VERSION_GSSNEGOTIATE, "GSS-Negotiate" },
                { CURL_VERSION_KERBEROS4, "Kerberos4" },
                { 0, NULL }
        };
        int resout = 0, i;
        curl_version_info_data *idata;
        CURL *curl;
        CURLcode res;

        curl_global_init(CURL_GLOBAL_DEFAULT);

        idata = curl_version_info(CURLVERSION_TENTH);
        (void)fprintf(stderr, "curl version: %s\n", idata->version);
        (void)fprintf(stderr, "curl ssl version: %s\n", idata->ssl_version);
        (void)fprintf(stderr, "curl protocols:\n");
        for (i = 0; idata->protocols[i]; ++i) {
                (void)fprintf(stderr, "\t%s\n", idata->protocols[i]);
        }
        (void)fprintf(stderr, "curl features:\n");
        for (i = 0; features[i].mask; ++i) {
                if (!(idata->features & features[i].mask)) {
                        continue;
                }
                (void)fprintf(stderr, "\t%s", features[i].name);
                if (!strcmp(features[i].name, "gsasl")
                                && idata->gsasl_version) {
                        (void)fprintf(stderr, " version %s\n",
                                idata->gsasl_version);
                } else if (!strcmp(features[i].name, "HTTP2")
                                && idata->nghttp2_version) {
                        (void)fprintf(stderr, " nghttp2 version %s\n",
                                idata->nghttp2_version);
                } else if (!strcmp(features[i].name, "HTTP3")
                                && idata->quic_version) {
                        (void)fprintf(stderr, " quic version %s\n",
                                idata->quic_version);
                } else {
                        (void)fprintf(stderr, "\n");
                }
        }
        if (idata->libssh_version) {
                (void)fprintf(stderr, "curl libssh version: %s\n",
                        idata->libssh_version);
        }
        if (idata->cainfo) {
                (void)fprintf(stderr, "curl default CAINFO: %s\n",
                        idata->cainfo);
        }
        if (idata->capath) {
                (void)fprintf(stderr, "curl default CAPATH: %s\n",
                        idata->capath);
        }
        
        curl = curl_easy_init();
        if (curl) {
                curl_easy_setopt(curl, CURLOPT_URL,
                               idata->nghttp2_version);
                } else if (!strcmp(features[i].name, "HTTP3")
                                && idata->quic_version) {
                        (void)fprintf(stderr, " quic version %s\n",
                                idata->quic_version);
                } else {
                        (void)fprintf(stderr, "\n");
                }
        }
        if (idata->libssh_version) {
                (void)fprintf(stderr, "curl libssh version: %s\n",
                        idata->libssh_version);
        }
        if (idata->cainfo) {
                (void)fprintf(stderr, "curl default CAINFO: %s\n",
                        idata->cainfo);
        }
        if (idata->capath) {
                (void)fprintf(stderr, "curl default CAPATH: %s\n",
                        idata->capath);
        }
        
        curl = curl_easy_init();
        if (curl) {
                curl_easy_setopt(curl, CURLOPT_URL,
                        "https://backwardseric.github.io/hengband/");
                /*
                 * Cache the CA cert bundle in memory for a week.
                 * This is not available with libcurl on macOS 12.6.7 with
                 * Xcode 14.2.
                 */
                /* curl_easy_setopt(curl, CURLOPT_CA_CACHE_TIMEOUT, 604800L); */
                res = curl_easy_perform(curl);
                if (res != CURLE_OK) {
                        (void)fprintf(stderr,
                                "curl_easy_perform() failed: %s\n",
                                curl_easy_strerror(res));
                        resout = 1;
                }
                curl_easy_cleanup(curl);
        } else {
                resout = 1;
        }
        curl_global_cleanup();
        return resout;
}
```

, on macOS 12.6.5 with Xcode 14.2 installed using ```cc -o junk -Wall -O -lcurl junk.c```. Then running it reports the following (I've truncated what was downloaded from the site):

```
curl version: 7.87.0
curl ssl version: (SecureTransport) LibreSSL/3.3.6
curl protocols:
        dict
        file
        ftp
        ftps
        gopher
        gophers
        http
        https
        imap
        imaps
        ldap
        ldaps
        mqtt
        pop3
        pop3s
        rtsp
        smb
        smbs
        smtp
        smtps
        telnet
        tftp
curl features:
        alt-svc
        AsynchDNS
        GSS-API
        HSTS
        HTTP2 nghttp2 version 1.45.1
        HTTPS-proxy
        IPv6
        Kerberos
        Largefile
        libz
        MultiSSL
        NTLM
        NTLM_WB
        SPNEGO
        SSL
        threadsafe
        UnixSockets
curl default CAINFO: /etc/ssl/cert.pem
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN"
   "http://www.w3.org/TR/1998/REC-html40-19980424/strict.dtd">
<HTML>
  <HEAD lang="en">
    <META http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <TITLE>Hengband Application for macOS</TITLE>
  </HEAD>
...
```

So it looks like it is using LibreSSL by default though MultiSSL support is there (does that require OpenSSL?).

**Comment by habu1010** [comment]
I see, so at least with libcurl, it is possible to distribute the encryption function library without static linking to the software.
By the way, MultiSSL seems to be a function to switch SSL backend by [curl_global_sslset](https://curl.se/libcurl/c/curl_global_sslset.html). Probably, if we specify CURLSSLBACKEND_OPENSSL, we can use OpenSSL (installed by homebrew).

Now, after much research and discussion with the development team, it seems to me that, generally speaking, open-source cryptographic libraries are not subject to U.S. cryptographic export restrictions.

This is stated in item "3." of the following text.
https://archive.epic.org/crypto/export_controls/regs_1_00.html

Also, [OpenSSL is actually distributed on GitHub](https://github.com/openssl/openssl), and I believe that redistribution of software using OpenSSL is not subject to the cryptographic export restrictions as long as the source code is accessible.

In any case, we intend to set up a configure switch to disable the SSL communication function for the time being, so we leave it up to you to decide what you want to do with the macOS version of the distribution.

**Comment by backwardsEric** [comment]
The notification requirements (under "3." in the document you linked) seem to be one source of trouble for software developers in the United States.  For instance, there's this description from someone at OpenSSL, https://mta.openssl.org/pipermail/openssl-users/2015-October/002186.html .  Given that notification requirements seem to be required for each release (which would presumably mean each entry at https://github.com/backwardsEric/hengband/releases ), I'd probably strip out the OpenSSL headers and libraries packaged with Hengband for Windows so they wouldn't be in the source archives for the macOS releases.  Depending on what's available from Hengband's configure script, the macOS binaries would be either linked against libcurl or configured with --disable-worldscore .

**Comment by habu1010** [comment]
Understood.
Based on our overall judgment, we will still revert to using libcurl for HTTP(S) communication.
Although SSL will no longer be available in cpp-httplib, we would like to create a libcurl wrapper class that implements the necessary functionality so that future HTTP(S) communication will be performed.

Thank you very much for your input.

**Comment by backwardsEric** [comment]
Finally set up a link to THIRD-PARTY-NOTICES.txt in the macOS application's about dialog.  That should resolve what is left from this issue.
