### ISSUE TITLE
Japanese version does not start on macOS14

### ISSUE THREAD

**Issue by tanguband** [backwardsEric/hengband#36]
## Environment

- OS: macOS14.1.1
- Version: Maybe all versions after changing to C++.

## Details

It crashes after giving the following message

Error on line 14612 of file 'MonsterRaceDefinitions.txt'.
Record 763 has 'missing argument' error.
Syntax 'D:：「へーえ？　父があんたを監禁したなんて、だれも知らなかった」　

## Additional Notes

I tried the following changes and built, and neither of them fail.

Before change 'D:：「へーえ？　父があんたを監禁したなんて、だれも知らなかった」　
After change 'D:　「へーえ？　父があんたを監禁したなんて、だれも知らなかった」　
(Change the double-byte '：' to '　')
<img width="763" alt="スクリーンショット 2023-11-22 13 56 42" src="https://github.com/backwardsEric/hengband/assets/17109188/66d26165-2ca1-4bdc-afa1-09508a09a1c8">
<img width="763" alt="スクリーンショット 2023-11-22 13 56 46" src="https://github.com/backwardsEric/hengband/assets/17109188/88aa40a5-422e-4f56-8158-3f62aa671fcc">
<img width="763" alt="スクリーンショット 2023-11-22 13 56 52" src="https://github.com/backwardsEric/hengband/assets/17109188/787f7174-64f5-4d04-9d9a-a111286c70e5">
<img width="763" alt="スクリーンショット 2023-11-22 13 56 57" src="https://github.com/backwardsEric/hengband/assets/17109188/954b879d-3c7e-4a31-8a06-b86ab65ef3a5">
<img width="372" alt="スクリーンショット 2023-11-22 13 57 03" src="https://github.com/backwardsEric/hengband/assets/17109188/df25b0da-cc98-4632-8ad2-767451f4040c">

**Comment by backwardsEric** [comment]
The Japanese version does start up for me on macOS 12.7.1.  For the system where it fails to start, is it using an Intel or Apple processor?

**Comment by tanguband** [comment]
It is Apple prosessor's macOS14.1.1 that will not boot.
The previously used intel macOS13.6.1 will boot.

The Alpha52~78 binaries that used to run on Apple prosessor macOS14.1.1 no longer run with the same message.
The version 2.2.1.7 does start.

**Comment by tanguband** [comment]
I checked and it did not start even on intel macos 14.1.1

**Comment by tanguband** [comment]
If you do not have a working environment with macos14 at hand, a fundamental solution may take some time.

As a temporary solution, I suggest the following changes

hengband/lib/edit/MonsterRaceDefinitions.txt 14611~14612

Before change
D:めている。…ドワーキン「こっちはオベロン様の捕虜だから」　コーウィン
D:：「へーえ？　父があんたを監禁したなんて、だれも知らなかった」　かれ

After the change
D:めている。…ドワーキン「こっちはオベロン様の捕虜だから」　コーウィン：
D:「へーえ？　父があんたを監禁したなんて、だれも知らなかった」　かれ

This change will allow it to run on macos14.

Please consider this.

**Comment by backwardsEric** [comment]
My guess is that the system's version of iconv() is changing the full-width colon to a standard colon when converting from UTF-8 to EUC-JP.  You could test that by compiling and running the following on macOS 14.1.1 (save it as junk.c then run "cc -Wall -o junk junk.c -liconv ; ./junk"):

```
#include <iconv.h>
#include <stdio.h>
#include <string.h>

int main(int args, char *argv[])
{
    /* Unicode's full-width colon, U+FF1A, is EF BC 9A in UTF-8. */
    char in[8] = ":\xEF\xBC\x9A", out[8];
    char *inp = in, *outp = out;
    size_t inl = 8, outl = 8;
    iconv_t cd = iconv_open("EUC-JP", "UTF-8");

    if (iconv(cd, &inp, &inl, &outp, &outl) != (size_t)-1) {
        (void)printf("Converted output: %s\n", out);
        if (strcmp(out, "::") == 0) {
            (void)printf("Full width colon converted to standard colon.\n");
        }
    }
    (void)iconv_close(cd);
    return 0;
}
```

I'd suggest an upstream change to replace info-reader/race-reader.cpp:147-160 with the following code:

```
        if (tokens.size() < 2 || buf.length() < 3) {
            return PARSE_ERROR_TOO_FEW_ARGUMENTS;
        }
#ifdef JP
        if (buf[2] == '$') {
            return PARSE_ERROR_NONE;
        }
        r_ptr->text.append(buf.substr(2));
#else 
        if (buf[2] != '$') {
            return PARSE_ERROR_NONE;
        }
        if (buf.length() == 3) {
            return PARSE_ERROR_TOO_FEW_ARGUMENTS;
        }
        append_english_text(r_ptr->text, buf.substr(3));
#endif
```

If that change is made, there should be similar changes made to the artifact parsing (info-reader/artifact-reader.cpp:89-108), base item parsing (info-reader/baseitem-reader.cpp:96-109), and dungeon parsing (info-reader/dungeon-reader.cpp:161-174) to prevent those from spuriously indicating too few arguments for lines that start with "D:：" or "D::".

If you can confirm that the iconv() is converting the full-width colon to a standard colon on macOS 14.1.1, I can submit an issue and proposed change to upstream Hengband for the handling of "D:：" and "D::" lines in the info files.  Until an upstream change is made, I'll apply your suggestion of avoiding the "D:：" line in MonsterRaceDefinitions.txt.

**Comment by tanguband** [comment]
Thanks for the detailed explanation.
Here are the results of the test code

$ cc -Wall -o junk junk.c -liconv ; ./junk
Converted output: ::
Full width colon converted to standard colon.

The results seem to be as expected, so I'm going to ask the development team of Hengband to correct the problem as you suggested.

**Comment by backwardsEric** [comment]
I submitted https://github.com/hengband/hengband/issues/3763 upstream.

**Comment by backwardsEric** [comment]
My proposal for resolving that issue is here: https://github.com/hengband/hengband/pull/3764 .

**Comment by backwardsEric** [comment]
The upstream changes have been committed to the develop branch.  In the prereleases, https://github.com/backwardsEric/hengband/releases/tag/vauto3.0.1-alpha2-e7a9eb5f8 has the temporary fix to avoid this issue at startup and https://github.com/backwardsEric/hengband/releases/tag/vauto3.0.1-alpha2-a9300903c (and all releases after it) has the upstream change but backs out the temporary fix.  Please let me know if there is any trouble with the latter prerelease on macOS 14.

**Comment by tanguband** [comment]
I have built commit_a9300903c on macos14 and confirmed that it works fine.
Thank you sincerely for making the pull request upstream!
We will close this issue.
