### ISSUE TITLE
Quest The Tower Crashing when moving to the second floor

### ISSUE THREAD

**Issue by tanguband** [backwardsEric/hengband#38]
## 環境

- OS: macos14.7.2
- バージョン: 3.0.1-Beta21-3f9b0b8c0
## バグの詳細

Fixed Quest Tower in Telmora 
Abnormal end when progressing to the second floor.

## 補足事項
GCU version built on Mac does not crash
https://github.com/hengband/hengband/issues/4718

**Comment by backwardsEric** [comment]
This was a regression introduced by https://github.com/backwardsEric/hengband/commit/f0684d27c9601cfd98ee0b992e04bc0353e00e69 (to merge in upstream's https://github.com/hengband/hengband/commit/2035c2d9fe43abc90870643cdc0f4a363be70fe9 ).  The full release, Hengband-3.0.1-Beta17 is affected as are all prereleases from May 17th, 2024 to December 14th, 2024.  The prerelease, https://github.com/backwardsEric/hengband/releases/tag/vauto3.0.1-beta21-3410f7b06 , fixes the problem.

If you have an affected version and don't want to change to a version without the bug, you add a newline to the end of Contents/Resources/lib/edit/quests/006_TheTower_2.txt in the application bundle to avoid the problem.
